erpcya/adempiere-vue

src/components/ADempiere/FilePathOrName/index.vue, src/components/ADempiere/Notification/index.vue, src/router/modules/ADempiere/menu.js, src/store/modules/ADempiere/processControl.js
Reverts erpcya/adempiere-vue#7
=> Revert "minimal changes"

src/components/ADempiere/ContextMenu/index.vue, src/components/ADempiere/Dialog/index.vue, src/components/ADempiere/Window/window.vue, src/store/modules/ADempiere/processControl.js
change emit event and listener by vuex state
=> change behavior of the modal dialog of the processes of the tabs

src/api/ADempiere/dictionary.js, src/components/ADempiere/Browser/index.vue, src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Field.vue, src/components/ADempiere/Process/index.vue, src/components/ADempiere/Tab/index.vue, src/components/ADempiere/Window/window.vue, src/store/modules/ADempiere/browser.js, src/store/modules/ADempiere/panel.js, src/store/modules/ADempiere/process.js
* Add paneltype in data().
* Add process list in browser.
* Delete unused methods.
* Add filter in fields displayed from browser.
=> Add process to browser and data table

src/utils/ADempiere/valueUtil.js
=> #feature/parse context

src/views/ADempiere/SearchWindow/datalist.json, src/views/ADempiere/SearchWindow/index.vue
* add button to eliminate filtering
=> minimal changes

src/components/ADempiere/ContextMenu/index.vue, src/components/ADempiere/DataTable/index.vue, src/store/modules/ADempiere/data.js
- bugfix data show in data table
- bugfix with context menu actions
=> some bugfix

src/views/ADempiere/ProcessActivity/index.vue
* The popover was added with the status of the process
*  it was added that the columns can be dragged and change the
=> Popover and drag

src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Date/index.vue, src/components/ADempiere/NumberBase/index.vue, src/components/ADempiere/Panel/detail.vue, src/components/ADempiere/Panel/index.vue, src/components/ADempiere/SearchTable/index.vue, src/components/ADempiere/TextAreaBase/index.vue, src/components/ADempiere/TextBase/index.vue, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue, src/views/ADempiere/Window/index.vue
* the detail panel is shown only when you have daughter windows
* fixed smart browser
* help from the text type field , text base , date  and number
=> adding style to the smart browser

package.json, src/api/ADempiere/data.js, src/store/modules/ADempiere/data.js, src/views/profile/components/recentItems.vue, src/views/profile/components/role.vue, src/views/profile/index.vue
Note: Please check the pull request first [gRPC-Data-Client 8](https://github.com/erpcya/gRPC-Data-Client/pull/8)
=> Add recent Items view and store.

src/components/ADempiere/ContextMenu/index.vue, src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Panel/index.vue, src/components/RightPanel/index.vue, src/views/ADempiere/ReportViewer/index.vue
* Report
* Optional fields
* configuration button
* detail panel size
=> style support

src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Field/fieldSize.js, src/components/RightPanel/index.vue, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue
* hiden search
* field yes and no size 3
* scroll
* configuration button
* help in popover
=> support scroll

src/components/ADempiere/Dropdown/index.vue
set all collapse opened in summary view
=> set collapse opened

src/api/ADempiere/data.js, src/components/ADempiere/Panel/filterFields.vue, src/store/modules/ADempiere/browserControl.js, src/store/modules/ADempiere/panel.js, src/utils/ADempiere/notification.js
* Search SB, if the field is isShowedFromUser is false,
and has some value.
* Search SB, if the field is isShowedFromUser is true, and has some value.
* Change the notification by a message, when a search is performed.
=> Add corect search to Smart Browser if change parameters.

src/views/ADempiere/Browser/index.vue
=> popover browser

src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue
=> support popover

src/views/ADempiere/ProcessActivity/index.vue
* process table activated the records are draggable
=> add drag Process ACtivity

src/components/ADempiere/DataTable/index.vue
* maintain the size of the column when editing
=> add column size

src/components/ADempiere/DataTable/index.vue, src/components/RightPanel/index.vue, src/views/ADempiere/SearchWindow/index.vue
* add property so that the tables are dragged
=> add drag Table

src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue
* add the help popover in the title
=> popover title

src/views/ADempiere/Window/index.vue
* correcting the width of the detail panel
=> Support PanelDetail

package.json, src/components/ADempiere/DataTable/index.vue, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/SearchWindow/index.vue
* add change of order in the table in descending order
=> change of order descending

src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Panel/searchCriteria.vue, src/store/modules/ADempiere/browser.js, src/store/modules/ADempiere/utils.js, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue, src/views/ADempiere/ReportViewer/index.vue
* support at the height of the table
* removing close button with icon x
* open parameters
=> add Search Criteria

package.json, src/views/ADempiere/SearchWindow/datalist.json, src/views/ADempiere/SearchWindow/index.vue
* add FIxed Column
* add Filter Column
=> /filterColumn

src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Panel/searchCriteria.vue, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/SearchWindow/index.vue
* height of the table with the registration counter and selectable
* Add Records table SearchWindow
=> Support SearchCriteria:

src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/Panel/searchCriteria.vue, src/views/ADempiere/Browser/index.vue
* adjusting title
* height of the table
* close button
=> align table and SearchCriteria

src/components/ADempiere/DataTable/filterColumns.vue, src/components/ADempiere/DataTable/index.vue, src/components/ADempiere/IconElement/index.vue, src/views/ADempiere/Browser/index.vue
* add style to the options button
* computer support
* Search support Criteria
=> Support collapse and  button option

src/layout/components/Sidebar/Logo.vue, src/router/modules/ADempiere/menu.js
* add route to profile
* add route to the dashboard
=> Redirecting to profile view

src/components/ADempiere/ContextMenu/index.vue, src/components/ADempiere/Panel/index.vue
* option to download visible only when it is report
=> MenuContext

src/store/modules/ADempiere/processControl.js, src/views/ADempiere/ProcessActivity/index.vue
* add the processes initiated to the server process list
=> support to process activity

src/components/ADempiere/ContextMenu/index.vue, src/views/ADempiere/ReportViewer/index.vue
* Alternate Menu for Reports Exceeds Limits
* There is no way to refresh a report
=> support ReportViewer

src/components/ADempiere/Panel/filterFields.vue, src/views/ADempiere/Browser/index.vue, src/views/ADempiere/Process/index.vue
* support for field filtering style
=> Support style of FilterFields

src/components/ADempiere/Date/index.vue
* validate mandatory parameters of date range type component
=> Validate parameters

src/components/ADempiere/DataTable/index.vue, src/views/ADempiere/Browser/index.vue
* adding icon
* support for the table
* smart Browser without scroll
=> Adding icon and support to the table

src/components/ADempiere/DataTable/index.vue, src/views/ADempiere/Window/index.vue
* correction of the navigation table search entry between records
=> search engine input correction

src/components/ADempiere/Panel/index.vue, src/components/ADempiere/badge/index.vue, src/store/modules/ADempiere/panel.js, src/store/modules/ADempiere/processControl.js, src/views/ADempiere/ProcessActivity/index.vue
* Support process activity and notification
* add process in notification
* support to relaunch reports
=> Support procces activity and notification

src/store/modules/ADempiere/panel.js
* correcting error the AvancedQuery
=> support GetPanel

src/components/ADempiere/Field/FieldDate.vue, src/views/ADempiere/Process/index.vue
* add option select last week range date
* adjust the height of the title of the processes and reports
=> support for the range date and the title of the processes and reports

src/store/modules/ADempiere/processControl.js
=> open report from the window
